### ISSUE TITLE
magisk not installed

### ISSUE THREAD

**Issue by NSTAdventure** [HuskyDG/Magisk-on-VMOS#1]
after trying all your step it won't work
using your vanilla rom 7.1.1
vmos pro global  1.0.3

**Comment by HuskyDG** [comment]
My Terminal Tool has some bugs with `post-fs-data` script caused by `/data/adb/script/post-fs-data.d/daemonsu.sh`, magisk can't be mounted. I have just fixed it. Please redownload my ROM or my Terminal Tool and delete `/data/adb/script/post-fs-data.d/daemonsu.sh`.
Sorry for this bug.

**Comment by NSTAdventure** [comment]
> My Terminal Tool has `post-fs-data` script bug caused by `/data/adb/script/post-fs-data.d/daemonsu.sh`, magisk can't be mounted. I have just fixed it. Please redownload my ROM or my Terminal Tool and delete `/data/adb/script/post-fs-data.d/daemonsu.sh`.
> Sorry for this bug.

also is turned out nor all app can trigger su request like debloater with magisk from f droid why? due to unstable?

also on xposed there is 2 framework systemless and normal which one is installed on this rom?
