### ISSUE TITLE
Rom no longer boot

### ISSUE THREAD

**Issue by NSTAdventure** [HuskyDG/Magisk-on-VMOS#2]
I use your vanilla rom 7.1.1 already instal magisk but it's looks like vmos won't boot that how to catch that booting log? @HuskyDG

**Comment by HuskyDG** [comment]
Install another VM, you can mount OT disks to secondary VM that allows you to access system files in other VMs:

https://github.com/HuskyDG/Mount-VMOSPro-OT-Disks

Try to delete `/etc/init/magisk.rc` file in that VM then reboot

**Comment by NSTAdventure** [comment]
Welp i reset my devices and lost everything i may try again to reproduce glitch

Regards
NST_Adventure
